[package]
org = "signup_app"
name = "signup_backend"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.1.0"